
# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mediai_db
spring.datasource.username=root
spring.datasource.password=password123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=mediai-backend

# Gemini
gemini.api.key=your-local-key-here
# JWT
jwt.secret=MediAISecretKey2024VeryLongSecretKeyForJWTTokenGenerationMustBe256Bits
jwt.expiration=86400000